# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setSpecialValueText("")
        self.doubleSpinBox.setAccelerated(False)
        self.doubleSpinBox.setProperty("showGroupSeparator", False)
        self.doubleSpinBox.setMaximum(360.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setWrapping(False)
        self.doubleSpinBox_2.setSpecialValueText("")
        self.doubleSpinBox_2.setAccelerated(False)
        self.doubleSpinBox_2.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_2.setMaximum(360.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_3.addWidget(self.doubleSpinBox_2, 0, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_3.setWrapping(False)
        self.doubleSpinBox_3.setSpecialValueText("")
        self.doubleSpinBox_3.setAccelerated(False)
        self.doubleSpinBox_3.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_3.setMaximum(360.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_5.setWrapping(False)
        self.doubleSpinBox_5.setSpecialValueText("")
        self.doubleSpinBox_5.setAccelerated(False)
        self.doubleSpinBox_5.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_5.setMaximum(360.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_2.addWidget(self.doubleSpinBox_5, 0, 1, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setWrapping(False)
        self.doubleSpinBox_4.setSpecialValueText("")
        self.doubleSpinBox_4.setAccelerated(False)
        self.doubleSpinBox_4.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_4.setMaximum(360.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 0, 2, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_8.setWrapping(False)
        self.doubleSpinBox_8.setSpecialValueText("")
        self.doubleSpinBox_8.setAccelerated(False)
        self.doubleSpinBox_8.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_8.setMaximum(360.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_2.addWidget(self.doubleSpinBox_8, 1, 1, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_7.setWrapping(False)
        self.doubleSpinBox_7.setSpecialValueText("")
        self.doubleSpinBox_7.setAccelerated(False)
        self.doubleSpinBox_7.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_7.setMaximum(360.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_2.addWidget(self.doubleSpinBox_7, 1, 2, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_9.setWrapping(False)
        self.doubleSpinBox_9.setSpecialValueText("")
        self.doubleSpinBox_9.setAccelerated(False)
        self.doubleSpinBox_9.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_9.setMaximum(360.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_2.addWidget(self.doubleSpinBox_9, 1, 0, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_6.setWrapping(False)
        self.doubleSpinBox_6.setSpecialValueText("")
        self.doubleSpinBox_6.setAccelerated(False)
        self.doubleSpinBox_6.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_6.setMaximum(360.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_2.addWidget(self.doubleSpinBox_6, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "3D Вращение"))
        self.doubleSpinBox.setPrefix(_translate("MainWindow", " X "))
        self.doubleSpinBox_2.setPrefix(_translate("MainWindow", " Y "))
        self.doubleSpinBox_3.setPrefix(_translate("MainWindow", " Z "))
        self.groupBox_2.setTitle(_translate("MainWindow", "4D Вращение"))
        self.doubleSpinBox_5.setPrefix(_translate("MainWindow", " YW "))
        self.doubleSpinBox_4.setPrefix(_translate("MainWindow", " ZW "))
        self.doubleSpinBox_8.setPrefix(_translate("MainWindow", " XZ "))
        self.doubleSpinBox_7.setPrefix(_translate("MainWindow", " ZY "))
        self.doubleSpinBox_9.setPrefix(_translate("MainWindow", " XY "))
        self.doubleSpinBox_6.setPrefix(_translate("MainWindow", " XW "))
