# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(967, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rotate_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rotate_x.setWrapping(False)
        self.rotate_x.setSpecialValueText("")
        self.rotate_x.setAccelerated(False)
        self.rotate_x.setProperty("showGroupSeparator", False)
        self.rotate_x.setMinimum(-360.0)
        self.rotate_x.setMaximum(360.0)
        self.rotate_x.setObjectName("rotate_x")
        self.gridLayout_3.addWidget(self.rotate_x, 0, 0, 1, 1)
        self.rotate_y = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rotate_y.setWrapping(False)
        self.rotate_y.setSpecialValueText("")
        self.rotate_y.setAccelerated(False)
        self.rotate_y.setProperty("showGroupSeparator", False)
        self.rotate_y.setMinimum(-360.0)
        self.rotate_y.setMaximum(360.0)
        self.rotate_y.setObjectName("rotate_y")
        self.gridLayout_3.addWidget(self.rotate_y, 0, 1, 1, 1)
        self.rotate_z = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rotate_z.setWrapping(False)
        self.rotate_z.setSpecialValueText("")
        self.rotate_z.setAccelerated(False)
        self.rotate_z.setProperty("showGroupSeparator", False)
        self.rotate_z.setMinimum(-360.0)
        self.rotate_z.setMaximum(360.0)
        self.rotate_z.setObjectName("rotate_z")
        self.gridLayout_3.addWidget(self.rotate_z, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rotate_zw = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_zw.setWrapping(False)
        self.rotate_zw.setSpecialValueText("")
        self.rotate_zw.setAccelerated(False)
        self.rotate_zw.setProperty("showGroupSeparator", False)
        self.rotate_zw.setMinimum(-360.0)
        self.rotate_zw.setMaximum(360.0)
        self.rotate_zw.setObjectName("rotate_zw")
        self.gridLayout_2.addWidget(self.rotate_zw, 0, 2, 1, 1)
        self.rotate_xz = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_xz.setWrapping(False)
        self.rotate_xz.setSpecialValueText("")
        self.rotate_xz.setAccelerated(False)
        self.rotate_xz.setProperty("showGroupSeparator", False)
        self.rotate_xz.setMinimum(-360.0)
        self.rotate_xz.setMaximum(360.0)
        self.rotate_xz.setObjectName("rotate_xz")
        self.gridLayout_2.addWidget(self.rotate_xz, 1, 1, 1, 1)
        self.rotate_yw = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_yw.setWrapping(False)
        self.rotate_yw.setSpecialValueText("")
        self.rotate_yw.setAccelerated(False)
        self.rotate_yw.setProperty("showGroupSeparator", False)
        self.rotate_yw.setMinimum(-360.0)
        self.rotate_yw.setMaximum(360.0)
        self.rotate_yw.setObjectName("rotate_yw")
        self.gridLayout_2.addWidget(self.rotate_yw, 0, 1, 1, 1)
        self.rotate_yz = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_yz.setWrapping(False)
        self.rotate_yz.setSpecialValueText("")
        self.rotate_yz.setAccelerated(False)
        self.rotate_yz.setProperty("showGroupSeparator", False)
        self.rotate_yz.setMinimum(-360.0)
        self.rotate_yz.setMaximum(360.0)
        self.rotate_yz.setObjectName("rotate_yz")
        self.gridLayout_2.addWidget(self.rotate_yz, 1, 2, 1, 1)
        self.rotate_xy = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_xy.setWrapping(False)
        self.rotate_xy.setSpecialValueText("")
        self.rotate_xy.setAccelerated(False)
        self.rotate_xy.setProperty("showGroupSeparator", False)
        self.rotate_xy.setMinimum(-360.0)
        self.rotate_xy.setMaximum(360.0)
        self.rotate_xy.setObjectName("rotate_xy")
        self.gridLayout_2.addWidget(self.rotate_xy, 1, 0, 1, 1)
        self.rotate_xw = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.rotate_xw.setWrapping(False)
        self.rotate_xw.setSpecialValueText("")
        self.rotate_xw.setAccelerated(False)
        self.rotate_xw.setProperty("showGroupSeparator", False)
        self.rotate_xw.setMinimum(-360.0)
        self.rotate_xw.setMaximum(360.0)
        self.rotate_xw.setObjectName("rotate_xw")
        self.gridLayout_2.addWidget(self.rotate_xw, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 76))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.min_w = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.min_w.setMinimum(-1000.0)
        self.min_w.setMaximum(1000.0)
        self.min_w.setObjectName("min_w")
        self.gridLayout_4.addWidget(self.min_w, 0, 0, 1, 1)
        self.position_w = QtWidgets.QSlider(self.groupBox_3)
        self.position_w.setOrientation(QtCore.Qt.Horizontal)
        self.position_w.setObjectName("position_w")
        self.gridLayout_4.addWidget(self.position_w, 0, 1, 1, 1)
        self.max_w = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.max_w.setMinimum(-1000.0)
        self.max_w.setMaximum(1000.0)
        self.max_w.setObjectName("max_w")
        self.gridLayout_4.addWidget(self.max_w, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "3D Вращение"))
        self.rotate_x.setPrefix(_translate("MainWindow", " X "))
        self.rotate_y.setPrefix(_translate("MainWindow", " Y "))
        self.rotate_z.setPrefix(_translate("MainWindow", " Z "))
        self.groupBox_2.setTitle(_translate("MainWindow", "4D Вращение"))
        self.rotate_zw.setPrefix(_translate("MainWindow", " ZW "))
        self.rotate_xz.setPrefix(_translate("MainWindow", " XZ "))
        self.rotate_yw.setPrefix(_translate("MainWindow", " YW "))
        self.rotate_yz.setPrefix(_translate("MainWindow", " YZ "))
        self.rotate_xy.setPrefix(_translate("MainWindow", " XY "))
        self.rotate_xw.setPrefix(_translate("MainWindow", " XW "))
        self.groupBox_3.setTitle(_translate("MainWindow", "4D Перемещение"))
        self.label.setText(_translate("MainWindow", "min W"))
        self.label_2.setText(_translate("MainWindow", "max W"))
